/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_Synth.h"
#include "VDAC_Synth.h"
#include "Pin_Synth_Out.h"
#include "Pin_Synth_Out_aliases.h"
#include "Timer_Synth.h"
#include "isr_Synth.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "DMA_Synth.h"
#include "RTC.h"
#include "CapSense.h"
#include "CapSense_Control.h"
#include "CapSense_Filter.h"
#include "CapSense_Processing.h"
#include "CapSense_Sensing.h"
#include "CapSense_Structure.h"
#include "CapSense_Tuner.h"
#include "CapSense_Configuration.h"
#include "CapSense_SensingCSD_LL.h"
#include "CapSense_RegisterMap.h"
#include "CapSense_SmartSense_LL.h"
#include "Thermistor.h"
#include "Pin_Vlow.h"
#include "Pin_Vlow_aliases.h"
#include "Pin_Vtherm.h"
#include "Pin_Vtherm_aliases.h"
#include "Pin_Vhi.h"
#include "Pin_Vhi_aliases.h"
#include "PVref.h"
#include "VrefBuffer.h"
#include "Pin_Vref.h"
#include "Pin_Vref_aliases.h"
#include "ADC.h"
#include "ADC_FILTER.h"
#include "VDAC_Synth_internalClock.h"
#include "VDAC_Synth_UAB.h"
#include "VDAC_Synth_UAB_CyUAB.h"
#include "VDAC_Synth_UAB_CyUAB_types.h"
#include "VDAC_Synth_UAB_CyUAB_regs.h"
#include "VDAC_Synth_UAB_param.h"
#include "VDAC_Synth_UAB_regs.h"
#include "VDAC_Synth_OUTBUFFER.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_SCB_IRQ.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "CapSense_ISR.h"
#include "ADC_intSarClock.h"
#include "ADC_IRQ.h"
#include "ADC_intUabClock.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

